### ISSUE TITLE
Need new index for anomaly view

### ISSUE THREAD

**Issue by mdittmer** [web-platform-tests/wpt.fyi#131]
https://master-dot-wptdashboard.appspot.com/interop/anomalies?browser=edge reports a Datastore indexing error:

```
API error 4 (datastore_v3: NEED_INDEX): no matching index found. recommended index is:
- kind: github.com.web-platform-tests.results-analysis.metrics.FailuresMetadata
  properties:
  - name: BrowserName
  - name: StartTime
    direction: desc
```
