### ISSUE TITLE
Version selection is broken in `/api/diff`

### ISSUE THREAD

**Issue by Hexcles** [web-platform-tests/wpt.fyi#298]
https://staging.wpt.fyi/api/diff?before=chrome@61df0b90ef&after=chrome-69@61df0b90ef

```
API error 4 (datastore_v3: NEED_INDEX): no matching index found. recommended index is:
- kind: TestRun
  properties:
  - name: Revision
  - name: BrowserVersion
    direction: desc
```

Looks like we just need a new index.
